apiVersion: v1
kind: Service
metadata:
  name: {{ include "another-nginx.fullname" . }}
  labels:
    {{- include "another-nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9113
      targetPort: exporter
      protocol: TCP
      name: exporter
  selector:
    {{- include "another-nginx.selectorLabels" . | nindent 4 }}
