{{- define "animal.configmap.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}
data: {}
{{- end -}}
{{- define "animal.configmap" -}}
{{- include "animal.util.merge" (append . "animal.configmap.tpl") -}}
{{- end -}}