apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unleash.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "unleash.name" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "postgres.labels" . | nindent 4 }}
data:
  init.sql: |-
    CREATE DATABASE unleash;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unleash.fullname" . }}-postgres
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "postgres.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: init-sql
          configMap:
            name: {{ include "unleash.fullname" . }}-postgres
            items:
            - key: init.sql
              path: init.sql
      containers:
        - name: postgres
          image: postgres:14.1-alpine3.15
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: init-sql
            mountPath: /docker-entrypoint-initdb.d/init.sql
            subPath: init.sql
            readOnly: true
          ports:
          - name: postgres
            containerPort: 5432
            protocol: TCP
          env:
          - name: POSTGRES_PASSWORD
            value: postgres_password
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unleash.fullname" . }}-postgres
  labels: {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  selector: {{- include "postgres.selectorLabels" . | nindent 4 }}
